# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(: ios)

platform :ios do
  desc "Build iOS app"
  lane :app_build do |options|
    scan(
      project: "TurboCalculator.xcodeproj",
      scheme: options[:scheme],
      device: options[:device],
      app_identifier: "QAGuru.Calculator",
      derived_data_path: "./QAGuruDD",
      build_for_testing: true
    )
  end

  desc "Run tests at iOS app"
  lane :app_test do |options|
    scan(
      derived_data_path: "./QAGuruDD",
      device: options[:device],
      test_without_building: true,
      result_bundle: true,
      app_identifier: "QAGuru.Calculator",
      scheme: options[:scheme],
      reset_simulator: true,
      output_directory: "Report",
      reinstall_app: true
    )
  end
end

